name: firebase_authentication_service
description: Package for Firebase Authentication
version: 0.0.1
homepage: https://www.jeffmilanes.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
    
flutter:
